.TH CREATE-PDNS-ZONES "1" "2018-01-03" "pdns-api-scripts" "PowerDNS REST API Scripts"

.SH NAME
create-pdns-zone \- Create a new zone in the local PowerDNS server via its rest API.

.SH SYNOPSYS
.B create-pdns-zone.sh
[options] zone.name.tld. primary.master.nameserver.tld.
        [supplementary.master.nameserver1.tld. ...]